In [58]:
from sqlalchemy import create_engine, text
import pandas as pd
from array import array
# install psycopg2

# Create CSV of hop_team_nashville for neo4j community detection algorithm

In [2]:
# Create engine
db_name = 'hop_team'

connection_string = f"postgresql://postgres:postgres@localhost:5432/{db_name}"

engine = create_engine(connection_string)

In [7]:
# Create hop_team csv for neo4j
query = '''
    SELECT
        referring_pcp_npi,
        receiving_hospital_npi,
        transaction_count
    FROM hop_team_nashville_mv;
'''

with engine.connect() as connection:
    hop_team_nashville_df = pd.read_sql(text(query), con=connection)

hop_team_nashville_df.to_csv('../data/hop_team_nashville.csv', index=False)

In [7]:
# Read hop_team community info
hop_team_community_df = pd.read_csv('../data/hop_team_community.csv')
hop_team_community_df.head(2)

          npi  communityId
0  1003013160         1423
1  1003050972         1438

# Referrals Analysis

In [89]:
(
    hop_team_community_df
        .groupby('communityId')
        .count()
        .sort_values(by='npi', ascending=False)
)

             npi
communityId
1438         380
1420         155
1399         130
1388         128
1424         116
1423         111
1439         104
1407          92
1442          61
1400          50
1390          36
1416          35
1403          29
1408          16

In [93]:
# Merge hop_team_nashville with hop_team_community
hop_team_nashville_community_df = (
    hop_team_nashville_df
        .merge(
            hop_team_community_df,
            left_on='referring_pcp_npi',
            right_on='npi',
            how='left'
        )
)
hop_team_nashville_community_df

,referring_pcp_npi,pcp,pcp_grouping,pcp_classification,pcp_specialization,receiving_hospital_npi,hospital,hospital_grouping,hospital_classification,hospital_specialization,patient_count,transaction_count,average_day_wait,std_day_wait,npi,communityId
0,1962515023,BELINDA BART,Allopathic & Osteopathic Physicians,Family Medicine,None,1891000923,"BEHAVIORAL HEALTHCARE CENTER AT COLUMBIA, LLC",Hospitals,Psychiatric Hospital,None,132,190,0.832,8.515,1962515023,1407
1,1467428680,RICHARD POWERS,Allopathic & Osteopathic Physicians,Family Medicine,None,1891000923,"BEHAVIORAL HEALTHCARE CENTER AT COLUMBIA, LLC",Hospitals,Psychiatric Hospital,None,125,196,0.153,1.819,1467428680,1407
2,1891708012,SHAWN GENTRY,Allopathic & Osteopathic Physicians,Family Medicine,None,1891000923,"BEHAVIORAL HEALTHCARE CENTER AT COLUMBIA, LLC",Hospitals,Psychiatric Hospital,None,141,195,0.287,3.271,1891708012,1407
3,1326048844,ANNA SZCZUKA,Allopathic & Osteopathic Physicians,Internal Medicine,None,1871530832,CENTRAL TENNESSEE HOSPITAL CORPORATION,Hospitals,General Acute Care Hospital,None,171,282,21.911,30.795,1326048844,1403
4,1831169069,ASHISH SONI,Allopathic & Osteopathic Physicians,Internal Medicine,Nephrology,1871530832,CENTRAL TENNESSEE HOSPITAL CORPORATION,Hospitals,General Acute Care Hospital,None,351,865,14.480,40.780,1831169069,1403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2780,1093818981,WALTER CLAIR,Allopathic & Osteopathic Physicians,Internal Medicine,Cardiovascular Disease,1265445506,WILLIAMSON COUNTY HOSPITAL DISTRICT,Hospitals,General Acute Care Hospital,None,40,74,35.527,48.210,1093818981,1438
2781,1396753356,WILLIAM BOGER,Allopathic & Osteopathic Physicians,Internal Medicine,None,1265445506,WILLIAMSON COUNTY HOSPITAL DISTRICT,Hospitals,General Acute Care Hospital,None,162,209,33.120,59.694,1396753356,1442
2782,1952304990,WILLIAM FLEET,Allopathic & Osteopathic Physicians,Internal Medicine,Cardiovascular Disease,1265445506,WILLIAMSON COUNTY HOSPITAL DISTRICT,Hospitals,General Acute Care Hospital,None,932,1300,15.931,41.599,1952304990,1442
2783,1699734798,WILLIAM HALFORD,Allopathic & Osteopathic Physicians,Family Medicine,None,1265445506,WILLIAMSON COUNTY HOSPITAL DISTRICT,Hospitals,General Acute Care Hospital,None,269,794,4.440,20.950,1699734798,1442
2784,1861430621,WILSON KEMP,Allopathic & Osteopathic Physicians,Internal Medicine,Cardiovascular Disease,1265445506,WILLIAMSON COUNTY HOSPITAL DISTRICT,Hospitals,General Acute Care Hospital,None,109,175,33.251,56.694,1861430621,1423

# Queries for Dashboard

In [94]:
# Filter by PCP specialty, hospital, or CBSA
query = '''
    SELECT *
    FROM hop_team_nashville_mv;
'''

with engine.connect() as connection:
    hop_team_nashville_df = pd.read_sql(text(query), con=connection)

hop_team_nashville_df.to_csv('../data/hop_team_nashville.csv', index=False)
hop_team_nashville_df.head(2)

,referring_pcp_npi,pcp,pcp_grouping,pcp_classification,pcp_specialization,receiving_hospital_npi,hospital,hospital_grouping,hospital_classification,hospital_specialization,patient_count,transaction_count,average_day_wait,std_day_wait
0,1962515023,BELINDA BART,Allopathic & Osteopathic Physicians,Family Medicine,None,1891000923,"BEHAVIORAL HEALTHCARE CENTER AT COLUMBIA, LLC",Hospitals,Psychiatric Hospital,None,132,190,0.832,8.515
1,1467428680,RICHARD POWERS,Allopathic & Osteopathic Physicians,Family Medicine,None,1891000923,"BEHAVIORAL HEALTHCARE CENTER AT COLUMBIA, LLC",Hospitals,Psychiatric Hospital,None,125,196,0.153,1.819

## Filter by PCP specialty, hospital, or CBSA.

In [29]:
# Get list of PCP specialties for selection
pcp_specialization_list = hop_team_nashville_df['pcp_specialization'].unique()
pcp_specialization_list

array([None, 'Nephrology', 'Cardiovascular Disease',
       'Clinical Cardiac Electrophysiology', 'Infectious Disease',
       'Gastroenterology', 'Hematology & Oncology', 'Pulmonary Disease',
       'Interventional Cardiology', 'Hematology', 'Medical Oncology',
       'Endocrinology, Diabetes & Metabolism',
       'Advanced Heart Failure and Transplant Cardiology',
       'Geriatric Medicine', 'Rheumatology',
       'Hospice and Palliative Medicine', 'Critical Care Medicine',
       'Addiction Medicine', 'Adult Medicine', 'Sports Medicine',
       'Sleep Medicine', 'Transplant Hepatology',
       'Adult Congenital Heart Disease', 'Hepatology',
       'Hypertension Specialist', 'Obesity Medicine',
       'Pediatric Cardiology', 'Pediatric Nephrology',
       'Pediatric Critical Care Medicine'], dtype=object)

In [41]:
specialization = 'Sleep Medicine'

# Filter based on PCP specialization input
if specialization == 'None':
    hop_team_nashville_df[hop_team_nashville_df['pcp_specialization'].isnull()]
else:
    hop_team_nashville_df[hop_team_nashville_df['pcp_specialization'] == specialization]

In [32]:
# Get list of hospital specialties for selection
hospital_specialization_list = hop_team_nashville_df['hospital_specialization'].unique()
hospital_specialization_list

array([None, 'Critical Access'], dtype=object)

In [42]:
specialization = 'Critical Access'

# Filter based on hospital specialization input
if specialization == 'None':
    hop_team_nashville_df[hop_team_nashville_df['hospital_specialization'].isnull()]
else:
    hop_team_nashville_df[hop_team_nashville_df['hospital_specialization'] == specialization]

## Visualize top referring PCPs and their referral patterns

In [62]:
# Get list of top referring PCPs based on number of referrals
top_referring_pcp_list = (
    hop_team_nashville_df
        .groupby('referring_pcp_npi')['transaction_count']
        .sum()
        .sort_values(ascending=False)
        .head()
        .index
        .to_list()
)
top_referring_pcp_list

[1417131715, 1174517593, 1679689285, 1043394166, 1104933738]

In [64]:
referring_pcp_npi = 1417131715

# Filter by top referring PCP
hop_team_nashville_df[hop_team_nashville_df['referring_pcp_npi'] == referring_pcp_npi]

,referring_pcp_npi,pcp,pcp_grouping,pcp_classification,pcp_specialization,receiving_hospital_npi,hospital,hospital_grouping,hospital_classification,hospital_specialization,patient_count,transaction_count,average_day_wait,std_day_wait
276,1417131715,JOHN RIDDICK,Allopathic & Osteopathic Physicians,Internal Medicine,Interventional Cardiology,1932146032,"HCA HEALTH SERVICES OF TENNESSEE, INC.",Hospitals,General Acute Care Hospital,None,597,689,9.848,28.841
277,1417131715,JOHN RIDDICK,Allopathic & Osteopathic Physicians,Internal Medicine,Interventional Cardiology,1023055126,"HCA HEALTH SERVICES OF TENNESSEE, INC.",Hospitals,General Acute Care Hospital,None,5571,9007,0.578,8.745
278,1417131715,JOHN RIDDICK,Allopathic & Osteopathic Physicians,Internal Medicine,Interventional Cardiology,1265487193,"HCA HEALTH SERVICES OF TENNESSEE, INC.",Hospitals,General Acute Care Hospital,Critical Access,88,98,41.653,50.372
279,1417131715,JOHN RIDDICK,Allopathic & Osteopathic Physicians,Internal Medicine,Interventional Cardiology,1750328852,"HCA HEALTH SERVICES OF TENNESSEE, INC.",Hospital Units,Psychiatric Unit,None,240,301,10.266,32.376
685,1417131715,JOHN RIDDICK,Allopathic & Osteopathic Physicians,Internal Medicine,Interventional Cardiology,1639123615,HTI MEMORIAL HOSPITAL CORPORATION,Hospital Units,Rehabilitation Unit,None,56,58,27.517,26.532
967,1417131715,JOHN RIDDICK,Allopathic & Osteopathic Physicians,Internal Medicine,Interventional Cardiology,1669567897,NORTHCREST MEDICAL CENTER,Hospitals,General Acute Care Hospital,None,104,118,48.364,59.098

## Summarize competitor referral patterns and network clusters

# Visuals for Presentation

Which PCP specialties or subgroups represent the largest potential growth opportunities for Vanderbilt. <br>
Key insights from the referral network and community structure. <br>
Recommendations for visualizations or dashboards that could support hospital decision-making.

In [6]:
# Filter by PCP specialty, hospital, or CBSA
query = '''
    SELECT *
    FROM hop_team_nashville_mv;
'''

with engine.connect() as connection:
    hop_team_nashville_df = pd.read_sql(text(query), con=connection)

hop_team_nashville_df.head(2)

,referring_pcp_npi,pcp,pcp_grouping,pcp_classification,pcp_specialization,receiving_hospital_npi,hospital,hospital_grouping,hospital_classification,hospital_specialization,patient_count,transaction_count,average_day_wait,std_day_wait
0,1962515023,BELINDA BART,Allopathic & Osteopathic Physicians,Family Medicine,None,1891000923,"BEHAVIORAL HEALTHCARE CENTER AT COLUMBIA, LLC",Hospitals,Psychiatric Hospital,None,132,190,0.832,8.515
1,1467428680,RICHARD POWERS,Allopathic & Osteopathic Physicians,Family Medicine,None,1891000923,"BEHAVIORAL HEALTHCARE CENTER AT COLUMBIA, LLC",Hospitals,Psychiatric Hospital,None,125,196,0.153,1.819

## Select hospitals and link to community specialty breakdown graph

## Create heatmap of referrals: hospitals x specialization
Purpose to show areas of opportunity for Vandy to grow

Which PCP specialties or subgroups represent the largest potential growth opportunities for Vanderbilt.
(Shannon: heatmap)
Key insights from the referral network and community structure.
(Abigail: community info)
Recommendations for visualizations or dashboards that could support hospital decision-making.
(Micheal: researching healthcare needs for creating recommendations)
Streamlit Dashboard
(Grant: Research app template)